TEMPLATE	= lib
CONFIG		= qt
TARGET		= qroll${BUILDMODEEXT}

#!include ../../config-local

INCBDIR	= roll

HEADERS = \
	struct/general.h \
	struct/workLevel.h \
	struct/series.h \
	struct/seriesAtari.h \
	struct/seriesRaw.h \
	struct/level.h \
	struct/levelAtari.h \
	struct/levelRaw.h \
	struct/atariFormat.h \
        struct/simpleLevel.h \
        struct/simpleLevel_d.h \
	struct/levelPar.h \
	struct/levelParam.h \
	struct/explosions.h \
	struct/blobDescr.h \
	struct/seriesManager.h \
	game/ball.h \
	game/button.h \
	game/conveyLever.h \
	game/conveyorBelt.h \
	game/detonator.h \
	game/documentation.h \
	game/dynamite.h \
	game/portcullis.h \
	game/openPortcullis.h \
	game/player.h \
	game/playerServer.h \
	game/spring.h \
	game/lift.h \
	game/miscEatable.h \
	game/foregroundElem.h \
	game/telepWall.h \
	game/keyGen.h \
	game/bomb.h \
	game/burningBomb.h \
	game/generator.h \
	game/rockGen.h \
	game/diamMonster.h \
	game/rockMonster.h \
	game/grassMonster.h \
	game/hungryMonster.h \
	game/lock.h \
	game/key.h \
	game/fallingEatable.h \
	game/diam.h \
	game/eatable.h \
	game/holeWall.h \
	game/permeabWall.h \
	game/transformWall.h \
	game/passingWall.h \
	game/blob.h \
	game/rightMonster.h \
	game/leftMonster.h \
	game/closeDoor.h \
	game/door.h \
	game/rock.h \
	game/backFactory.h \
	game/back.h \
	game/elemFactory.h \
	game/roll.h \
	game/spritFlag.h \
	game/init.h \
	game/constantes.h \
	game/game.h \
	game/vars.h \
	game/gElem.h \
        game/random.h \
	gui/gameField.h \
	gui/qGameField.h \
        gui/qglGameField.h \
	gui/qAbout.h \
	gui/clientDialog.h \
	gui/playField.h \
	gui/scoreBox.h \
	gui/mainWin.h \
        gui/configWin.h \
        gui/gameConfig.h \
	gui/glcontext.h \
        gui/editPalette.h \
	gui/levelParams.h \
        gui/painter.h \
        gui/seriesArranger.h \
        gui/seriesIconView.h \
	gui/qdatastreamWrapper.h \
	sound/alsaProcessor.h \
	sound/dsp.h \
	sound/qsound.h \
	sound/soundProcessor.h \
	socket/qPlayerServer.h \
	socket/playerServerSocket.h \
	socket/singleSocket.h \
	socket/netMessages.h

SOURCES = \
	struct/workLevel.cc \
	struct/series.cc \
	struct/seriesAtari.cc \
	struct/seriesRaw.cc \
	struct/level.cc \
	struct/levelAtari.cc \
	struct/levelRaw.cc \
        struct/simpleLevel.cc \
	struct/explosions.cc \
	struct/blobDescr.cc \
	struct/seriesManager.cc \
	game/dynamite.cc \
	game/detonator.cc \
	game/conveyLever.cc \
	game/button.cc \
	game/ball.cc \
	game/portcullis.cc \
	game/openPortcullis.cc \
	game/player.cc \
	game/playerServer.cc \
	game/spring.cc \
	game/lift.cc \
	game/conveyorBelt.cc \
	game/miscEatable.cc \
	game/foregroundElem.cc \
	game/telepWall.cc \
	game/keyGen.cc \
	game/bomb.cc \
	game/burningBomb.cc \
	game/generator.cc \
	game/rockGen.cc \
	game/diamMonster.cc \
	game/rockMonster.cc \
	game/grassMonster.cc \
	game/hungryMonster.cc \
	game/lock.cc \
	game/key.cc \
	game/fallingEatable.cc \
	game/diam.cc \
	game/eatable.cc \
	game/holeWall.cc \
	game/permeabWall.cc \
	game/transformWall.cc \
	game/passingWall.cc \
	game/blob.cc \
	game/rightMonster.cc \
	game/leftMonster.cc \
	game/closeDoor.cc \
	game/door.cc \
	game/rock.cc \
	game/backFactory.cc \
	game/back.cc \
	game/elemFactory.cc \
	game/roll.cc \
	game/init.cc \
	game/game.cc \
	game/vars.cc \
	game/gElem.cc \
        game/random.cc \
	gui/qGameField.cc \
	gui/gameField.cc \
        gui/qglGameField.cc \
	gui/qAbout.cc \
	gui/clientDialog.cc \
	gui/scoreBox.cc \
	gui/playField.cc \
	gui/mainWin.cc \
        gui/configWin.cc \
        gui/gameConfig.cc \
	gui/glcontext.cc \
        gui/editPalette.cc \
	gui/levelParams.cc \
        gui/painter.cc \
        gui/seriesArranger.cc \
        gui/seriesIconView.cc \
	gui/simpleLevelIO.cc \
	sound/alsaProcessor.cc \
	sound/dsp.cc \
	sound/qsound.cc \
	sound/soundProcessor.cc \
	socket/qPlayerServer.cc \
	socket/playerServerSocket.cc \
	socket/netMessages.cc
