#!/bin/sh

osname=`uname -s`
case "${osname}" in
SunOS)
	os=solaris;;
Linux)
	os=linux;;
IRIX*)
	os=irix;;
esac

ROLL=/home/riviere/devel/qroll
ROLLDIR=${ROLL}/dependencies
ROLLEXE=${ROLL}-${os}
LD_LIBRARY_PATH=${ROLLEXE}/lib:$LD_LIBRARY_PATH
export ROLLDIR LD_LIBRARY_PATH

${ROLLEXE}/bin/qroll
